### ISSUE TITLE
Misleading hint on missing key-based ssh authentication

### ISSUE THREAD

**Issue by rgiordani** [nikvdp/pbproxy#3] opened 2022-12-30 10:16 UTC
The readme says: "make sure you have key-based ssh authentication set up (otherwise you'll have to enter your password each time you copy or paste)". Not quite so for copy, because the input would mix up with the password, not allowing entering it.

I suggest to add `-o "KbdInteractiveAuthentication no"` to ssh invocations, at least for copy, to prevent the issue.

**Comment by nikvdp** [comment] 2022-12-30 15:27
Are you able to reproduce this? I disabled my ssh keys and tested briefly and pbcopy works as expected because ssh (smartly) reads the password from `/dev/tty` rather than stdin to prevent exactly the situation you're describing. 

Closing for now, but if you are able to reproduce this please reopen and share the repro steps!

**Closed as completed by nikvdp** 2022-12-30 15:27 UTC

**Comment by rgiordani** [comment] 2022-12-30 16:01
Sorry, I was wrong. As you said, It reads the password from `/dev/tty`.

**Comment by nikvdp** [comment] 2022-12-30 16:27
No worries, appreciate the thought!
